### PR TITLE
83 token storage and refresh 

### LINKED ISSUE #83: token storage and refresh
Implement secure token storage and session refresh. The access token is stored only in frontend memory. The refresh token is stored in a secure HttpOnly cookie. If the access token expires, the app should refresh it. If refresh fails, the session is cleared and the user is redirected to /login.

### LINKED ISSUE #87: docker-up: add health checks / startup readiness
I noticed that sometimes after `make docker-up`, users-sv exits with "Connection to database refused" (DB not ready yet). If I restart users later, it works. Could we add DB readiness handling in compose, and optionally a restart policy for users?

### PR DESCRIPTION
**Pull request by mariyakulikova**
Target changes:
- store access token only in frontend memory
- move refresh token handling to secure HttpOnly cookie
- update frontend auth flow to use shared session manager and automatic refresh
- retry authorized requests after refresh and clear session on refresh failure
- redirect unauthorized users to /login

Verification:
- `make docker-up`
- open `https://localhost:8443/`
- sign in with test@test.test / 1234
- reload a protected page and verify the session is restored through refresh
- sign out and verify the app redirects to `/login`
- reload again and verify the session is not restored after logout

### CODE REVIEW

File: deployment/users/startup.sh [hunk 1]
```diff
@@ -1,3 +1,14 @@
...
+# Wait for database to be ready before starting the JVM.
+if [ -f /bin/bash ]; then
+  until /bin/bash -c "echo > /dev/tcp/database/${DATABASE_CONTAINER_PORT:-5432}" 2>/dev/null; do
+    echo "Waiting for database (via bash /dev/tcp)..."
+    sleep 2
+  done
+else
+  echo "Bash not found, skipping wait and hoping for the best..."
+fi
+
```
Comment (mariyakulikova) [inline deployment/users/startup.sh:13]: added a db readiness check to avoid a startup race where the users service boots before postgres is ready to accept connections

**Review by DitaBisko — APPROVED** [review]
Thank you Maria! Great work, solid security and implementation. Thank you so much!

**Review by owrmille — APPROVED** [review]
ദ്ദി(˵ •̀ ᴗ - ˵ ) ✧

**Comment by mariyakulikova** [comment]
thank you, ladies, I really appreciate it! 💃
