### PR TITLE
80 fix frontend backend api contract mismatch

### LINKED ISSUE #80: fix frontend-backend api contract mismatch
Update the frontend integration layer to match the current backend public API.

Examples:
- `/opinionLists/*` -> `/opinion-lists/*`
- `/accessRequests/*` -> `/access-requests/*`
- `/opinions/id?id=...` -> `/opinions/{id}`
- `/opinions/for?subjectId=...` -> `/opinions/for/{subjectId}`
- `/selectors/forSubject` -> `/selectors/for-subject/{subjectId}`

### PR DESCRIPTION
**Pull request by mariyakulikova**
Target change:
- aligned frontend API modules with current backend endpoint paths and request parameters
- fixed selectors.disagree to match the backend contract
- added contract tests for routes, methods, auth headers, and query/path params

Verification:
- `make frontend-install-all`
- `make frontend-test-unit`

### CODE REVIEW

**Review by owrmille — APPROVED** [review]

File: frontend/src/lib/api/access-requests.ts [hunk 1]
```diff
@@ -60,45 +60,45 @@ export function createAccessRequestsApi(client: HttpClient = httpClient) {
...
       request: AccessRequestActionRequestDto,
     ): Promise<AccessRequestDto> {
-      return client.post<AccessRequestDto>("/accessRequests/incoming/accept", {
-        headers: createAuthorizationHeaders(request.accessToken),
-        query: {
-          requestId: request.requestId,
+      return client.post<AccessRequestDto>(
+        `/access-requests/incoming/${request.requestId}/accept`,
+        {
+          headers: createAuthorizationHeaders(request.accessToken),
```
Comment (ioannnikulin) [inline frontend/src/lib/api/access-requests.ts:66]: do we need auth first?

Comment (mariyakulikova) [reply frontend/src/lib/api/access-requests.ts:66]: @ioannnikulin this is from the old auth stub on the frontend. real auth is not ready yet, so we can update this later when proper authentication is implemented

Comment (ioannnikulin) [reply frontend/src/lib/api/access-requests.ts:66]: auth seems mostly ready

Comment (mariyakulikova) [reply frontend/src/lib/api/access-requests.ts:66]: @ioannnikulin I will do it in next PR. this pr contains fix. it should be merged

Comment (mariyakulikova) [reply frontend/src/lib/api/access-requests.ts:66]: @ioannnikulin it contains fixes for endpoint routes and unit tests related to the http client. it is not related to auth

**Review by DitaBisko — APPROVED** [review]
Looks good to me.
